app = "setcookie"

[env]
  APP_ENV = "production"
  ASSET_MAP = "/config/assets.map"

[[services]]
  internal_port = 80

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = false

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"
