name: Add Deploy Preview Comment
on:
  workflow_run:
    workflows: New Pull Request
    types: completed
jobs:
  comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: 'github-actions[bot]'
          body-includes: Your deploy preview
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ steps.number.outputs.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: >
            Your deploy preview can be found at https://setcookie-staging-${{ github.event.workflow_run.pull_requests[0].number }}.fly.dev.
