# Warning: This has access to secrets and checks out untrusted code. Modify with caution
# This uses pull_request/workflow_run instead of pull_request_target so it needs to be approved

name: Create Deploy Preview
on:
  workflow_run:
    workflows: New Pull Request
    types: completed

jobs:
  get-number:
    name: Get PR number
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      number: ${{ steps.number.outputs.number }}
      app-name: setcookie-staging-${{ steps.number.outputs.number }}
    steps:
      - name: Find PR number
        id: number
        run: |
          number=$(curl -s ${{ github.event.workflow_run.jobs_url }} |
            jq -r '.jobs[0].steps | map(select(.number == 2)) | first.name')
          echo "number=$number" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest
    needs: get-number
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    environment:
      name: ${{ needs.get-number.outputs.app-name }}
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy preview app
        id: deploy
        run: |
          app_name="${{ needs.get-number.outputs.app-name }}"
          echo "url=https://$app_name.fly.dev" >> $GITHUB_OUTPUT

          flyctl apps list | grep "$app_name" || flyctl apps create "$app_name"
          flyctl deploy --remote-only -a "$app_name" -e APP_ENV=staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  comment:
    runs-on: ubuntu-latest
    needs: [get-number, deploy]
    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v3
        id: find-comment
        with:
          issue-number: ${{ needs.get-number.outputs.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Your deploy preview

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ needs.get-number.outputs.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: >
            Your deploy preview can be found at ${{ needs.deploy.outputs.url }}.
