name: Close Pull Request
on:
  pull_request_target:
    types: closed
    branches: main
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Destroy preview app
        run: |
          flyctl apps destroy -y "setcookie-staging-${{ github.event.number }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Delete environment
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          output=$(gh api -X DELETE repos/{owner}/{repo}/environments/setcookie-staging-${{ github.event.number }}) || code=$?
          echo "$output"
          [ ${code:-0} -eq 0 -o $(jq -re .status <<< $output || echo 0) -eq 404 ] || exit $code
