name: Close Pull Request
on:
  pull_request:
    types: closed
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/download-artifact@v3
        with:
          name: app-pr${{ github.event.pull_request.number }}
      - name: Destroy preview app
        id: destroy
        run: |
          app_name="$(jq .Name < app.json)"
          flyctl apps destroy -y $app_name
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - uses: geekyeggo/delete-artifact@v2
        with:
          name: app-pr${{ github.event.pull_request.number }}
