name: New Pull Request
on:
  pull_request:
    branches: main

concurrency:
  group: staging-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.number }}
        run: true
