name: New Pull Request
on:
  pull_request:
    branches: main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy preview app
        run: |
          app_name="setcookie-staging-${{ github.event.pull_request.number }}"
          flyctl apps list | grep "$app_name" || flyctl apps create "$app_name"
          flyctl deploy --remote-only -a "$app_name" -e APP_ENV=staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
